# Generated by Django 4.1.5 on 2023-01-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
