# Generated by Django 4.1.5 on 2023-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_jobseekerusernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregisterinfo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobseekerusernames',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
