# Generated by Django 4.1.5 on 2023-01-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_jobseekerregisterinfo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='username',
        ),
    ]
