# Generated by Django 4.1.5 on 2023-01-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_remove_jobseekerregisterinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='last_name',
        ),
    ]
