# Generated by Django 4.1.5 on 2023-01-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_remove_jobseekerregisterinfo_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobseekerUsernames',
        ),
    ]
