# Generated by Django 4.1.5 on 2023-01-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobseekerregisterinfo',
            managers=[
            ],
        ),
    ]
