# Generated by Django 4.1.5 on 2023-01-12 22:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_jobseekerregisterinfo_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobseekerregisterinfo',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
