# Generated by Django 4.1.5 on 2023-01-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_alter_jobseekerregisterinfo_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='hashed_password',
        ),
    ]
