# Generated by Django 4.1.5 on 2023-01-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_remove_jobseekerregisterinfo_hashed_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerregisterinfo',
            options={},
        ),
        migrations.AlterModelManagers(
            name='jobseekerregisterinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='jobseekerregisterinfo',
            name='user_permissions',
        ),
    ]
