# Generated by Django 4.1.5 on 2023-01-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0014_alter_jobseekerregisterinfo_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
