# Generated by Django 4.1.5 on 2023-01-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0015_delete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregisterinfo',
            name='login',
            field=models.CharField(default='user_without_login', max_length=100),
        ),
    ]
