# Generated by Django 4.1.5 on 2023-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_jobseekerregisterinfo_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregisterinfo',
            name='login',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
