# Generated by Django 4.1.5 on 2023-01-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0017_alter_jobseekerregisterinfo_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='avatars/%Y/%m/%d')),
                ('header', models.TextField(blank=True)),
                ('skype', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('whats_app', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('git_hub', models.URLField(blank=True)),
                ('cv', models.FileField(upload_to='cv/%Y/%m/%d')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
