# Generated by Django 4.1.5 on 2023-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0018_jobseekerprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofileinfo',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofileinfo',
            name='whats_app',
        ),
        migrations.AddField(
            model_name='jobseekerprofileinfo',
            name='active_search',
            field=models.BooleanField(default=True),
        ),
    ]
