# Generated by Django 4.1.5 on 2023-03-02 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import personal_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=190)),
            ],
        ),
        migrations.CreateModel(
            name='RelativeWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_expectations', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.PositiveIntegerField(blank=True)),
                ('experience', models.CharField(choices=[('0', '0'), ('0.6', '0.6'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10')], default='0', max_length=5)),
                ('moving_to_another_city', models.BooleanField(default=False)),
                ('work_experience', models.TextField(blank=True)),
                ('expectations', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('questions_to_employers', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.category')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.city')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.country')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.position')),
                ('relative_way', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.relativeway')),
                ('speaking_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.speakinglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='JobseekerProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('expected_job', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=150)),
                ('linkedin', models.URLField(blank=True)),
                ('git_hub', models.URLField(blank=True)),
                ('cv_file', models.FileField(upload_to='cvs/%Y/%m/%d', validators=[personal_profile.models.validate_file_extension])),
                ('active_search', models.BooleanField(default=True)),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
