# Generated by Django 4.1.5 on 2023-01-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofileinfo',
            name='header',
        ),
        migrations.AddField(
            model_name='jobseekerprofileinfo',
            name='expected_job',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
