# Generated by Django 4.1.5 on 2023-03-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.RemoveField(
            model_name='workcriteria',
            name='relative_way',
        ),
        migrations.RemoveField(
            model_name='workcriteria',
            name='speaking_language',
        ),
        migrations.DeleteModel(
            name='RelativeWay',
        ),
        migrations.DeleteModel(
            name='SpeakingLanguage',
        ),
    ]
