# Generated by Django 4.1.5 on 2023-01-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0002_remove_jobseekerprofileinfo_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofileinfo',
            name='photo',
            field=models.ImageField(default='static/personal_profile/images/default_avatar.png', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
