# Generated by Django 4.1.5 on 2023-01-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0003_alter_jobseekerprofileinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofileinfo',
            name='telegram',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
