# Generated by Django 4.1.5 on 2023-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0004_alter_jobseekerprofileinfo_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofileinfo',
            name='cv',
            field=models.FileField(upload_to='cvs/%Y/%m/%d'),
        ),
    ]
