# Generated by Django 4.1.5 on 2023-03-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0004_speakinglanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcriteria',
            name='speaking_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.speakinglanguage'),
        ),
    ]
