# Generated by Django 4.1.5 on 2023-02-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0007_alter_jobseekerprofileinfo_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofileinfo',
            name='cv_file',
            field=models.FileField(upload_to='cvs/%Y/%m/%d'),
        ),
    ]
