# Generated by Django 4.1.5 on 2023-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0009_alter_jobseekerprofileinfo_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofileinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d'),
        ),
    ]
