# Generated by Django 4.1.5 on 2023-03-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0012_category_city_country_position_workcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcriteria',
            name='experience',
            field=models.CharField(choices=[('0', '0'), ('0.6', '0.6'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10')], default='0', max_length=5),
        ),
    ]
